#!/usr/bin/env python3
"""
Strip non-essential metadata from article frontmatter.

Moves workflow/tracking metadata from index.md into a local .metadata.yml
file (gitignored), keeping only publishing-relevant fields in the
committed markdown.

Usage:
  python3 strip-metadata.py            # apply stripping
  python3 strip-metadata.py --dry-run  # preview without writing
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List, Tuple

REPO_ROOT = Path(__file__).parent
FRONTMATTER_BOUNDARY = "---"
METADATA_FILENAME = ".metadata.yml"

# Fields allowed to remain in index.md (pushed to GitHub).
# Compared case-insensitively against frontmatter keys.
# NOTE: title and updatedAt/publishedAt are also kept because they are
# required by validate-articles.py (pre-push validation).
ALLOWED_FIELDS_LOWER = {
    "title",
    "link to repo",
    "projects",
    "one liner",
    "tags",
    "summary",
    "series",
    "platform",
    "cover_image",
    "cover image",
    "updatedat",
    "publishedat",
    "status"
}

MARKDOWN_INDEX_NAMES = {"index.md", "index.markdown"}
IGNORED_NAMES = {
    ".git", ".github", ".venv", "__pycache__", "node_modules",
    "publish", "public", "build", "dist",
}

RESET = "\033[0m"
GREEN = "\033[32m"
YELLOW = "\033[33m"
BOLD = "\033[1m"
CYAN = "\033[36m"
DIM = "\033[2m"


def discover_article_dirs(repo_root: Path) -> List[Path]:
    """Find all article directories containing an index.md."""
    dirs: List[Path] = []
    for entry in sorted(repo_root.iterdir(), key=lambda p: p.name.lower()):
        if not entry.is_dir() or entry.name.startswith("."):
            continue
        if entry.name.lower() in {n.lower() for n in IGNORED_NAMES}:
            continue
        for candidate in MARKDOWN_INDEX_NAMES:
            if (entry / candidate).exists():
                dirs.append(entry)
                break
    return dirs


def process_article(article_dir: Path, dry_run: bool = False) -> Tuple[int, int]:
    """
    Strip non-allowed fields from frontmatter and save to .metadata.yml.
    Returns (fields_stripped, fields_kept).
    """
    index_path = None
    for candidate in MARKDOWN_INDEX_NAMES:
        p = article_dir / candidate
        if p.exists():
            index_path = p
            break

    if index_path is None:
        return 0, 0

    text = index_path.read_text(encoding="utf-8").lstrip("\ufeff")

    if not text.startswith(FRONTMATTER_BOUNDARY):
        return 0, 0

    lines = text.replace("\r\n", "\n").split("\n")

    # Find closing frontmatter boundary
    closing_idx = None
    for i in range(1, len(lines)):
        if lines[i].strip() == FRONTMATTER_BOUNDARY:
            closing_idx = i
            break

    if closing_idx is None:
        return 0, 0

    fm_lines = lines[1:closing_idx]
    allowed_fm: List[str] = []
    stripped_fm: List[str] = []
    current_key_allowed: bool | None = None
    stripped_count = 0
    kept_count = 0

    for line in fm_lines:
        s = line.strip()

        # Blank line — keep only if previous key was allowed (avoid orphan blanks)
        if not s:
            if current_key_allowed is not False:
                allowed_fm.append(line)
            continue

        # Continuation line (YAML list item or indented value)
        if s.startswith("- ") or (line and line[0] in (" ", "\t")):
            if current_key_allowed:
                allowed_fm.append(line)
            else:
                stripped_fm.append(line)
            continue

        # Key: value line
        if ":" in line:
            key = line.split(":", 1)[0].strip()
            is_allowed = key.lower() in ALLOWED_FIELDS_LOWER
            current_key_allowed = is_allowed

            if is_allowed:
                allowed_fm.append(line)
                kept_count += 1
            else:
                stripped_fm.append(line)
                stripped_count += 1
        else:
            # Unknown line, keep
            allowed_fm.append(line)

    if stripped_count == 0:
        return 0, kept_count

    # Trim trailing blank lines from allowed frontmatter
    while allowed_fm and not allowed_fm[-1].strip():
        allowed_fm.pop()

    # Reconstruct index.md with only allowed fields
    new_lines = [lines[0]] + allowed_fm + lines[closing_idx:]
    new_text = "\n".join(new_lines)

    # Build .metadata.yml content
    meta_lines = [
        "# Local-only metadata (not pushed to GitHub)",
        "# Auto-generated by strip-metadata.py",
    ]
    meta_lines.extend(stripped_fm)
    meta_content = "\n".join(meta_lines) + "\n"

    metadata_path = article_dir / METADATA_FILENAME

    if dry_run:
        rel = article_dir.relative_to(REPO_ROOT)
        print(f"  {CYAN}Would strip {stripped_count} field(s), keep {kept_count}{RESET}")
        for ln in stripped_fm:
            ls = ln.strip()
            if ":" in ls and not ls.startswith("- "):
                print(f"    {YELLOW}– {ls.split(':', 1)[0].strip()}{RESET}")
    else:
        index_path.write_text(new_text, encoding="utf-8")
        metadata_path.write_text(meta_content, encoding="utf-8")

    return stripped_count, kept_count


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Strip non-essential metadata from article frontmatter"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Preview changes without writing files"
    )
    args = parser.parse_args()

    articles = discover_article_dirs(REPO_ROOT)
    if not articles:
        print("No articles found.")
        return 0

    total_stripped = 0
    modified = 0

    for article_dir in articles:
        rel = article_dir.relative_to(REPO_ROOT)
        stripped, kept = process_article(article_dir, dry_run=args.dry_run)

        if stripped > 0:
            prefix = "Would modify" if args.dry_run else "Modified"
            print(f"{GREEN}{prefix}: {rel}/index.md{RESET} "
                  f"({stripped} stripped, {kept} kept)")
            modified += 1

        total_stripped += stripped

    verb = "Would strip" if args.dry_run else "Stripped"
    print(f"\n{BOLD}{verb} {total_stripped} field(s) from {modified} article(s){RESET}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
